---
# Main task entry point for viper.setup

- name: "SSH | Disallow root login."
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes$'
    replace: 'PermitRootLogin no'
    backup: yes
  notify: restart ssh

- name: "SSH | Disallow password authentication."
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes$'
    replace: 'PasswordAuthentication no'
  notify: restart ssh

- name: "SSH | Disable IPv6 access."
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#AddressFamily any$'
    replace: 'AddressFamily inet'
  notify: restart ssh

- name: "SSH | Install first boot host key generation unit."
  copy:
    src: "files/etc/systemd/system/viper-regenerate-host-keys.service"
    dest: "/etc/systemd/system/viper-regenerate-host-keys.service"
    owner: "root"
    group: "root"
    mode: '0644'

- name: "SSH | Enable first boot host key generation."
  systemd:
    name: "viper-regenerate-host-keys.service"
    enabled: yes
    daemon_reload: yes
