---
# Main task entry point for viper.setup

- name: "SSH | Disallow root login."
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes$'
    replace: 'PermitRootLogin no'
    backup: yes
  notify: restart ssh

- name: "SSH | Disallow password authentication."
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes$'
    replace: 'PasswordAuthentication no'
  notify: restart ssh

- name: "SSH | Disable IPv6 access."
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#AddressFamily any$'
    replace: 'AddressFamily inet'
  notify: restart ssh
