---
# Main task entry point for viper.setup

- name: "IPTABLES V4 | Allow all loopback (lo0) traffic."
  iptables:
    chain: INPUT
    in_interface: "lo"
    jump: ACCEPT
    comment: "Allow all loopback (lo0) traffic"

- name: "IPTABLES V4 | Reject localhost that doesn't originate from lo0."
  iptables:
    chain: INPUT
    in_interface: "lo"
    source: "!127.0.0.0/8"
    jump: REJECT
    comment: "Reject localhost that doesn't originate from lo0"

- name: "IPTABLES V4 | Allow Ping."
  iptables:
    chain: INPUT
    protocol: icmp
    ctstate: NEW
    icmp_type: 8
    jump: ACCEPT
    comment: "Allow ping"

- name: "IPTABLES V4 | Allow SSH."
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow SSH connections"

- name: "IPTABLES V4 | Allow HTTP."
  iptables:
    action: insert
    chain: INPUT
    in_interface: "{{ item }}"
    protocol: tcp
    destination_port: "{{ viper.setup.port.http }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow HTTP connections"
  with_items: "{{ viper.setup.iptables.interfaces }}"
  when: viper.setup.port.http is defined and viper.setup.port.http != ""

- name: "IPTABLES V4 | Allow port traffic from proxy."
  iptables:
    action: insert
    chain: INPUT
    source: "{{ opf_proxy_private_ip }}"
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow TCP connections on port: {{ item }}"
  when: opf_proxy_private_ip is defined and opf_proxy_private_ip != ""
  with_items: "{{ viper.setup.open_ports }}"

- name: "IPTABLES V4 | Allow HTTPS."
  iptables:
    action: insert
    chain: INPUT
    in_interface: "{{ item }}"
    protocol: tcp
    destination_port: "{{ viper.setup.port.https }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "Allow HTTP connections"
  with_items: "{{ viper.setup.iptables.interfaces }}"
  when: viper.setup.port.https is defined and viper.setup.port.https != ""

- name: "IPTABLES V4 | Allow inbound traffic from established connections."
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: "Allow inbound traffic from established connections"

- name: "IPTABLES V4 | Log what was incoming but denied."
  iptables:
    chain: INPUT
    limit: "5/min"
    jump: LOG
    log_prefix: "iptables_INPUT_denied: "
    comment: "Log what was incoming but denied (optional but useful)"

- name: "IPTABLES V4 | Reject all other inbound."
  iptables:
    chain: INPUT
    jump: REJECT
    comment: "Reject all other inbound"

- name: "IPTABLES V4 | Log Traffic sent for forwarding."
  iptables:
    chain: INPUT
    limit: "5/min"
    jump: LOG
    log_prefix: "iptables_FORWARD_denied: "
    comment: "Log Traffic sent for forwarding (optional but useful)"

- name: "IPTABLES V4 | Reject all traffic forwarding."
  iptables:
    chain: FORWARD
    jump: REJECT
    comment: "Reject all traffic forwarding"
