---
# Main task entry point for viper.setup

- name: "IMPORT | IPTABLES rules for IPV4."
  import_tasks: ipv4-rules.yml
  when: viper.setup.ip.v4 is defined and viper.setup.ip.v4 != ""

- name: "IMPORT | IPTABLES rules for IPV6."
  import_tasks: ipv6-rules.yml
  when: viper.setup.ip.v6 is defined and viper.setup.ip.v6 != ""

- name: "IMPORT | Set up persistence for IPTABLES."
  import_tasks: iptables-persistent.yml
