- hosts: docker-viper
  become: true
  roles:
    - { role: viper.setup }
    - { role: viper.tools }

# docker host specfic actions
# put the desktop icons in the right place
- hosts: docker-viper
  tasks:
    - name: DOCKER Tools | Install xfconf-query
      apt:
        name: xfconf
        state: present

    - name: Set desktop background to custom image
      command: >
        xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace0/last-image -s /usr/local/share/backgrounds/viper-desktop.jpg

    - name: DOCKER Tools | Hide Home icon from desktop
      command: >
        xfconf-query -c xfce4-desktop -p /desktop-icons/file-icons/show-home -n -t bool -s false

    - name: DOCKER Tools | Hide Filesystem icon from desktop
      command: >
        xfconf-query -c xfce4-desktop -p /desktop-icons/file-icons/show-filesystem -n -t bool -s false

    - name: DOCKER Tools | Hide Trash icon from desktop
      command: >
        xfconf-query -c xfce4-desktop -p /desktop-icons/file-icons/show-trash -n -t bool -s false

    - name: DOCKER Tools | Install rsync
      apt:
        name: rsync
        state: present

    - name: DOCKER Tools | Synchronize viper Desktop to vnc abc user home folder
      command: rsync -av /home/viper/Desktop/ /config/Desktop/
      become: yes
      become_user: root

    - name: DOCKER tools | Change ownership of all files in Desktop folder
      command: sudo chown -R abc:abc /config/Desktop
      become: yes

    - name: DOCKER tools | Mark executable files in Desktop folder
      command: find /config/Desktop -type f -exec chmod a+x {} \;
      become: yes

    - name: Get list of all files in Desktop folder
      find:
        paths: /config/Desktop
        patterns: "*.desktop"
        file_type: file
      register: desktop_files

    - name: DOCKER tools | Make all desktop launchers executable
      file:
        path: "{{ item.path }}"
        mode: '0755'
      loop: "{{ desktop_files.files }}"
      become: yes

    # - name: DOCKER tools | Wait for the folder to be created
    #   ansible.builtin.wait_for:
    #     path: /config/.local/share/gvfs-metadata
    #     state: present
    #     timeout: 300  # Adjust the timeout as needed

    # - name: DOCKER tools | Set metadata::xfce-exe-checksum for each .desktop file
    #   shell: >
    #     dbus-launch gio set -t string {{ item.path }} metadata::xfce-exe-checksum "$(sha256sum {{ item.path }} | awk '{print $1}')"

    #   loop: "{{ desktop_files.files }}"
    #   become: true
    #   become_user: abc
    
    - name: Create scripts folder /usr/local/share/scripts
      file:
        path: "/usr/local/share/scripts"
        state: directory
        mode: '0755'

    - name: Copy script to /usr/local/share/scripts/post-install.sh
      copy:
        src: ../docker-files/post-install.sh
        dest: "/usr/local/share/scripts/post-install.sh"
        mode: '0755'

    - name: Ensure the script is executable by all users
      ansible.builtin.file:
        path: /usr/local/share/scripts/post-install.sh
        mode: 'a+x'        

    - name: Add sudoers rule for script execution
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/abc
        create: yes
        line: 'abc ALL=(ALL) NOPASSWD: /usr/local/share/scripts/post-install.sh'
        validate: '/usr/sbin/visudo -cf %s'
      become: true

    - name: Create autostart folder /config/.config/autostart
      file:
        path: "/config/.config/autostart"
        state: directory
        mode: '0755'

    - name: Create autostart entry for post-install script
      ansible.builtin.copy:
        dest: /config/.config/autostart/post-install.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Exec=sudo /usr/local/share/scripts/post-install.sh
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name[en_US]=Post Install Script
          Name=Post Install Script
          Comment[en_US]=Run post-install script at login
          Comment=Run post-install script at login
        owner: abc
        group: abc
        mode: '0644'
