---

# Packer inventory for provisioning
all:
  vars:
    viper_env_timezone: "Europe/Berlin"
    viper_env_ip: "{{ ansible_ssh_host }}"
    opf_server_hostname: "viper"
    opf_server_hostdomain: "viper.test"
    opf_server_fqdn: "{{ opf_server_hostname }}.{{ opf_server_hostdomain }}"
  hosts:
    default:
      ansible_connection: ssh
      ansible_ssh_user: vagrant
