FROM lscr.io/linuxserver/webtop:debian-xfce-48fa8b80-ls90
# FROM docker-kasmvnc-darrenopf  

ENV TITLE="ViPER Cloud"

COPY favicon.ico /ksuite/public/favicon.ico
COPY apple-touch-icon.png /ksuite/public/icon.png

EXPOSE 3000