---
# Prerequisites for viper.setup

# openjdk-17 setup requires this path exist before we continue inside a container.
- name: "APT | Ensure /usr/share/man/man1/ directory exists"
  file:
    path: /usr/share/man/man1/
    state: directory
    mode: '0755'

- name: "APT | Install apt package pre-requisites."
  apt:
    name: "{{ viper.setup.prereqs.apt }}"
    state: "latest"

- name: "LOCALE | Set up common locale packages."
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ viper.setup.locales }}"
  notify:
    - rebuild locales database

- name: "LOCALE | Set default locale."
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ viper.setup.default_locale }}"
    vtype: select
  notify:
    - rebuild locales database

- name: "LOCALE | Setup keyboard defaults."
  copy:
    src: "files/etc/default/keyboard"
    dest: "/etc/default/keyboard"

- name: "GRUB | Configure GRUB to skip boot menu."
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=0'
    backup: yes
  notify: update grub configuration
  when: ansible_virtualization_type != "docker"

- name: "GRUB | Hide GRUB menu for faster boot."
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT_STYLE='
    line: 'GRUB_TIMEOUT_STYLE=hidden'
    insertafter: '^GRUB_TIMEOUT='
  notify: update grub configuration
  when: ansible_virtualization_type != "docker"

- name: "APT | Remove unnecessary packages."
  apt:
    name: "{{ viper.setup.remove.apt }}"
    state: "absent"
    purge: yes
    autoremove: yes
